### ISSUE TITLE
Can this only use the sdk provided by you?

### ISSUE THREAD

**Issue by ZiHengLee** [ProjectOpenSea/stream-js#107]
can we use stream api by golang?
Maybe the documentation can be improved a little bit for other language users, I hope to get your reply, thank you

**Comment by arnauddorgans** [comment]
Edit: You can find the first version of the SDK here: https://github.com/arnauddorgans/OpenSeaSwift

**Comment by itsthedoom** [comment]
Hello, @ZiHengLee did @arnauddorgans and @rohfle answers help?

**Comment by rohfle** [comment]
@ZiHengLee - foundVanting created an (untested by me) golang library to do this in #122  - see https://github.com/foundVanting/opensea-stream-go

**Comment by itsthedoom** [comment]
@the-emerald Nioce!!

**Comment by jerempjerem** [comment]
Hi just made this in python https://github.com/jerempjerem/opensea-stream-py
