### ISSUE TITLE
May I subscribe event only be interested in?

### ISSUE THREAD

**Issue by HuHa** [ProjectOpenSea/stream-js#111]
It's possible to filter event type not on the client but on the server? Having 90+% bid and offer events I'm not interested in, not only burst traffic and also wastes CPU, memory, IO, etc.

**Comment by itsthedoom** [comment]
@HuHa confirming @rohfle response worked? 
If not please let us know and we can reopen this issue. 
Please note the API Stream is in Beta, we will be adding additional features in the future, please check the [changelog](https://docs.opensea.io/changelog)and repo for updates.
