### ISSUE TITLE
The Info log shows Successfully joined channel "collection:*",But there is no data push

### ISSUE THREAD

**Issue by liyawawa** [ProjectOpenSea/stream-js#115]
<img width="790" alt="image" src="https://user-images.githubusercontent.com/20918902/168538167-bc22a238-85f3-47d0-bed4-1d1137704864.png">

**Comment by itsthedoom** [comment]
@liyawawa are you still running into issues? Did you test subscribing to events? 
[Connecting & Subscribing to Events ](https://docs.opensea.io/reference/stream-api-overview#connecting--subscribing-to-events)

The streaming rate depends on a range of factors - from the amount of collections that you’re monitoring to the type and amount of events that you’re subscribed to. For instance, if you’re subscribed to receive bid events across all collections on OpenSea, you’ll be receiving messages at a significantly higher rate than you will for a subscription to order cancellations on a small collection.
