### ISSUE TITLE
how to connect wss://stream.openseabeta.com/socket using python websocket?

### ISSUE THREAD

**Issue by wei-dai** [ProjectOpenSea/stream-js#117]
I am not very good at js, I want to connect wss://stream.openseabeta.com/socket using python, but I always get 404 error when try to connect wss://stream.openseabeta.com/socket. Is there any tutorial on using python?

Thanks in advance!

**Comment by rohfle** [comment]
try `wss://stream.openseabeta.com/socket/websocket?token=API_TOKEN&vsn=2.0.0`
references: 
https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix/socket.js#L144
https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix/socket.js#L176

example code
```python
url = "wss://stream.openseabeta.com/socket/websocket?token=API_TOKEN&vsn=2.0.0"
import websockets
import asyncio
async def hello(uri):
    async with connect(uri) as websocket:
        print("CONNECTED")

asyncio.run(hello(url))


```

**Comment by hubba-bubba-776** [comment]
Im getting 403 error for some reason

**Comment by rohfle** [comment]
So to follow up on this, while my example above works, stream-js uses the Phoenix Channels protocol on top of websocket, which has its own quirks  (heartbeat, channel joining etc)

See related in golang https://github.com/ProjectOpenSea/stream-js/issues/122

There are a couple of existing Phoenix Channels libraries for python here, but I haven't tested them
https://github.com/supabase-community/realtime-py
https://github.com/obmarg/chunnel

Otherwise its roll your own, but you'd have to study the Phoenix Channels protocol or other implementations to do this

**Comment by zpencerguy** [comment]
> try `wss://stream.openseabeta.com/socket/websocket?token=API_TOKEN&vsn=2.0.0` references: https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix/socket.js#L144 https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix/socket.js#L176
> 
> example code
> 
> ```python
> url = "wss://stream.openseabeta.com/socket/websocket?token=API_TOKEN&vsn=2.0.0"
> from websockets import connect
> import asyncio
> async def hello(uri):
>     async with connect(uri) as websocket:
>         print("CONNECTED")
> 
> asyncio.run(hello(url))
> ```

Would you be able to provide a short example snippet of code of how to subscribe to a channel using the Phoenix Channels protocol with python? Thanks 🙏

**Comment by matthieuoliveira** [comment]
@zpencerguy you come across a snippet yet?

**Comment by rjbks** [comment]
I believe there is one in the docs now.

**Comment by matthieuoliveira** [comment]
@rjbks are you referring to [this](https://docs.opensea.io/reference/using-stream-api-without-sdk) doc?

If so, when I connect to the server, I attempt to send the heartbeat and or collection subscription schema and receive error code 1011.

**Comment by matthieuoliveira** [comment]
@rjbks Issue was using vsn=2.0.0 in my connection string 
@zpencerguy I should be able to supply you with a snippet shortly

**Comment by zpencerguy** [comment]
Thank you @matthieuoliveira, that will be super helpful!
