### ISSUE TITLE
Can't connect to testnet

### ISSUE THREAD

**Issue by rick-rheo** [ProjectOpenSea/stream-js#118]
With code

```
import { OpenSeaStreamClient } from '@opensea/stream-js';
import { WebSocket } from 'ws';

const client = new OpenSeaStreamClient({
  network: Network.TESTNET,
  token: MYAPIKEY    <-  I use an actual key here  (also tried with no key at all since this is testnet)
  connectOptions: {
    transport: WebSocket
  }
});
```

I get

```
05/17 09:22:50-07:00::[ERROR]: Unexpected server response: 403 

    at e.n.error (/Users/dev/os/node_modules/@opensea/stream-js/dist/index.cjs:121:54)
    at v (/Users/dev/os/node_modules/@opensea/stream-js/dist/index.cjs:33:13)
    at /Users/dev/os/node_modules/phoenix/priv/static/phoenix.cjs.js:987:7
    at Array.forEach (<anonymous>)
    at Socket.onConnError (/Users/dev/os/node_modules/phoenix/priv/static/phoenix.cjs.js:986:37)
    at WebSocket.conn.onerror (/Users/dev/os/node_modules/phoenix/priv/static/phoenix.cjs.js:873:41)
    at WebSocket.onError (/Users/dev/os/node_modules/ws/lib/event-target.js:220:18)
    at WebSocket.emit (node:events:527:28)
    at emitErrorAndClose (/Users/dev/os/node_modules/ws/lib/websocket.js:984:13)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

```

with the actual code I get  [ERROR} : [object, Object]    but I modified the code to write out  e.message

Connecting to MAINNET seems to work though I can't verify since we don't have anything live there yet.

**Comment by lllapland** [comment]
Same here.

**Comment by rohfle** [comment]
You don't need the API key for the testnet APIs
See this announcement from 2 days ago https://docs.opensea.io/changelog/testnets-api-no-longer-requires-an-api-key

**Comment by rick-rheo** [comment]
@rohfle   still fails with no api key  (as specified in the original report)

**Comment by meixianjie** [comment]
Same here

**Comment by laubsauger** [comment]
Fails with and without API key in `token` field.

**Comment by rossgardt** [comment]
Having the same issue here 😕

**Comment by FighterAircraft** [comment]
Having the same issue here

**Comment by ninjasploit** [comment]
We're all in the same boat!

**Comment by rick-rheo** [comment]
I'm pretty sure this is a dead project. There's no recent commits and absolutely no response to any recent issues from anyone at OpenSea.

**Comment by itsthedoom** [comment]
Are you still having issues connecting to testnet? 
The following blockchains are supported on Testnet networks:

Rinkeby
Polygon testnet (Mumbai)
Klaytn testnet (Baobab)

Have you reviewed the [Stream API Overview (Beta) docs?](https://docs.opensea.io/reference/stream-api-overview).

If you are still running into issues can you please let me know?

**Comment by ninjasploit** [comment]
For anyone lucky enough to have an API key, you can use the opensea "mainnet" and play around with it there

**Comment by tino-web** [comment]
Still the same problem here. Mainnet is nice, but you can't really test for example orders there...

**Comment by xiaoliangxin** [comment]
I have the same problem, how can I solve it？？

**Comment by alexejFroebel** [comment]
Any news?

**Comment by esteban-OpenSea** [comment]
An API key for Testnets is no longer required. If you want to use the API in Mainnet, an API key is required. If you don’t have an API key, [request one from us](https://docs.opensea.io/reference/request-an-api-key). This should fix the error you are running into.

https://docs.opensea.io/reference/stream-api-overview#:~:text=Do%20I%20need%20an%20API%20key%20for%20Mainnet%20and%20Testnet%20to%20use%20the%20Stream%20API%3F

**Comment by rick-rheo** [comment]
> An API key for Testnets is no longer required. If you want to use the API in Mainnet, an API key is required. If you don’t have an API key, [request one from us](https://docs.opensea.io/reference/request-an-api-key). This should fix the error you are running into.
> 
> https://docs.opensea.io/reference/stream-api-overview#:~:text=Do%20I%20need%20an%20API%20key%20for%20Mainnet%20and%20Testnet%20to%20use%20the%20Stream%20API%3F

You didn't read the bug or even try this.  I am NOT sending an API key.

**Comment by esteban-OpenSea** [comment]
I used to get the same error message. Before we pushed out an update on this, you needed two different api keys. One for mainnet and one for testnet. You cannot use a mainnet api key when using testnets, vice versa. So this should fix the issue. Please try running now and let me know if you get the same error. If you continue having issues, we can troubleshoot it.

**Comment by esteban-OpenSea** [comment]
Also, we encourage all devs to join our community of web3 builders on Discord https://discord.gg/opensea
