### ISSUE TITLE
tried to use stream-api in golang but handshake failed

### ISSUE THREAD

**Issue by xrmzju** [ProjectOpenSea/stream-js#122]
i tried to use opensea stream-api in golang through the a stand implemention of websocket protocal (https://github.com/gorilla/websocket), but got `handshake error`.  i digged into the response and found the server returned 404 not found to the upgrade request, does opensea stream api server not implement in standard websocket?  or should i try socket.io?

here is my example code
```go
func main() {
	flag.Parse()
	log.SetFlags(0)

	interrupt := make(chan os.Signal, 1)
	signal.Notify(interrupt, os.Interrupt)

	u, _ := url.Parse("wss://stream.openseabeta.com/socket")
	log.Printf("connecting to %s", u.String())

	c, _, err := websocket.DefaultDialer.Dial(u.String(), nil)
	if err != nil {
		log.Fatal("dial:", err)
	}
	defer c.Close()

	done := make(chan struct{})

	go func() {
		defer close(done)
		for {
			_, message, err := c.ReadMessage()
			if err != nil {
				log.Println("read:", err)
				return
			}
			log.Printf("recv: %s", message)
		}
	}()
	select {}
}
```

**Comment by rohfle** [comment]
stream-js is built on top of [phoenix](https://github.com/phoenixframework/phoenix/tree/33a72c8fb9c9fcd36de4ccfe6f6a5abba4b6609c/assets/js/phoenix), which implements a protocol with its own quirks (heartbeat, channel joining etc)

You might want to use an existing Phoenix Channels library for go like:
https://github.com/nshafer/phx

If you want to roll your own still, see https://github.com/ProjectOpenSea/stream-js/issues/117 for correct url - this will fix the 404

https://github.com/ProjectOpenSea/stream-js/blob/main/src/client.ts
https://github.com/ProjectOpenSea/stream-js/blob/main/src/types.ts#L26
^ good starting points for how it works ... start with the onItemSold function and follow the function calls down

**Comment by xrmzju** [comment]
> tart with the onItemSold function and follow the function calls down

thank you very much for your detailed explanation,i'll give it a try later

**Comment by itsthedoom** [comment]
@xrmzju did @rohfle recommendations work for you?

**Comment by itsthedoom** [comment]
Closing this issue. If the recommendations did not work please let me know.

**Comment by foundVanting** [comment]
I followed rohfle advice and it work
https://github.com/foundVanting/opensea-stream-go 
Welcome star！
