### ISSUE TITLE
Streaming multiple events does not work

### ISSUE THREAD

**Issue by HappySprinkles** [ProjectOpenSea/stream-js#128]
The supplied code for streaming multiple events does not work it results in the following error: ReferenceError: EventType is not defined
The supplied code is 
`client.onEvents(
  '*',
  [EventType.ITEM_RECEIVED_OFFER, EventType.ITEM_TRANSFERRED],
  (event) => {
    console.log(event)
  }
);`

**Comment by itsthedoom** [comment]
@HappySprinkles is [Streaming multiple event types](https://github.com/ProjectOpenSea/stream-js#streaming-multiple-event-types) still not working for you? 

```
client.onEvents(
  'collection-slug',
  [EventType.ITEM_RECEIVED_OFFER, EventType.ITEM_TRANSFERRED],
  (event) => {
    // handle event
  }
);
```
