### ISSUE TITLE
Ethereum  only  

### ISSUE THREAD

**Issue by ntop001** [ProjectOpenSea/stream-js#129]
When set `collection:*` it receives all the events from etheruem/polygon/solana, How can we get only events from etheruem? I don't want to filter these events in the client, Since it's too much data, and almost used up my bandwidth.

**Comment by ntop001** [comment]
And I also found that the `event_type` just filter events at the client side,  it's receiving all the  listings/offers/transfers/solds , and most of them maybe useless if I wanna only listings or transfers.

**Comment by itsthedoom** [comment]
@ntop001 did you have a chance to review [Connecting & Subscribing to Events ](https://docs.opensea.io/reference/stream-api-overview#connecting--subscribing-to-events ) Each subscription function includes a collectionSlug parameter which can be used to subscribe to an event from a specific collection.

**Comment by ntop001** [comment]
@itsthedoom Sir, if you want only ethereum events, you have to subscribe tens of thousands collections slugs, I don't think that's the right way to use collectionSlug params.

**Comment by itsthedoom** [comment]
@ntop001 can you share your use case? You can also listen to specific events you're interested in e.g. [Streaming multiple event types ](https://github.com/ProjectOpenSea/stream-js#streaming-multiple-event-types)

[Streaming item listed events](https://github.com/ProjectOpenSea/stream-js#streaming-item-listed-events)
```
client.onItemListed('collection-slug', (event) => {
  // handle event
});
```

[Streaming item transferred events](https://github.com/ProjectOpenSea/stream-js#streaming-item-transferred-events)
```
client.onItemTransferred('collection-slug', (event) => {
  // handle event
});
```

**Comment by ntop001** [comment]
@itsthedoom My use case is to subscribe all the events and all the collections from Ethereum(not solana, not polygon).  I know there is one way to do this, just subscribe `collection:*` , but if you subscribe   `collection:*`, it'll also stream events from solana/polygon.  I also know that I can filter these events at client side, but It'll produces large amount of traffics and use up all my bandwidth. So what I need is a better StreamAPI, which can subscribe only events from ethereum, likes: `event: ethereum`. I have read the docs many times,  and I also read the source of the stream-sdk, I know how the stream-js works. It's too simple and it does have any API to implements this feature.

**Comment by ntop001** [comment]
@itsthedoom and obviously，use these code: `client.onItemListed('collection-slug', (event) => {` , you can only subscribe to  one collection, but what if you want to subscribe to all the collections from ethereum ??

**Comment by itsthedoom** [comment]
@ntop001 got it; diving a little deeper, are you looking to subscribe to all collections or something more similar to the [Activity Feed](https://opensea.io/activity) or [Rankings Feed](https://opensea.io/rankings)?

**Comment by fmaduakor** [comment]
Would be great to be able to subscribe to specific networks. I need to subscribe to all offer events on ethereum, but right now stream api creates alot of unnecessary traffic.
