### ISSUE TITLE
New Feature Request - Order Transaction details

### ISSUE THREAD

**Issue by steddyman** [ProjectOpenSea/stream-js#135]
Opening a new Issue because the last one was closed in error without a resolution.  Original details below:

The details returned from the streaming API when monitoring for onItemListedEvents does not return any information that can be used to identify or place a buy order. There are is no order hashes included or any of the other details that can be used to directly locate the corresponding order.  

There is no easy way using the REST API to identify the order that triggered the notification and even if there was, it defeats the purpose of using the streaming API to make users then use the REST API to seach through multiple orders to identify the triggering order.

**Comment by itsthedoom** [comment]
@steddyman Thank you for the feedback; we will share this request with the team.

**Comment by i5possible** [comment]
Could we have the token id as well? Once the token is listed, we even don't know which one is listed.
