### ISSUE TITLE
keep throwing [ERROR]: [object Object]

### ISSUE THREAD

**Issue by neicras** [ProjectOpenSea/stream-js#136]
Hi there,

I am following a few of your sample codes and each end up keep throwing "[ERROR]: [object Object]"

Code:
`client.onEvents(
    '*',
    [osstream.EventType.ITEM_LISTED, osstream.EventType.ITEM_RECEIVED_OFFER],
    (event) => {
        console.log(event)
    }
);`

<img width="292" alt="Screenshot 2022-06-06 at 6 36 58 PM" src="https://user-images.githubusercontent.com/33999550/172145433-eaa03552-0028-4f3d-974b-0a98bda94b14.png">

Kindly advise!
br
neic

**Comment by itsthedoom** [comment]
@neicras are you testing on the MAINNET or TESTNET? 
Can you provide a sample code and steps to help us reproduce this error?

**Comment by rohfle** [comment]
@neicras when you create the `OpenSeaStreamClient` instance, what function do you set for `onError` ?

I have:
```js
const client = new OpenSeaStreamClient({
  // ... rest of arguments
  onError: (obj) => console.error(obj.message, obj.error),
});
```

**Comment by neicras** [comment]
> @neicras are you testing on the MAINNET or TESTNET? Can you provide a sample code and steps to help us reproduce this error?

Cool. Just a simple piece of code like this:

const osstream = require('@opensea/stream-js');
const WebSocket = require('ws');

const client = new osstream.OpenSeaStreamClient({
    token: '***',
    connectOptions: {
        transport: WebSocket
    },
});

client.onEvents(
    '*',
    [osstream.EventType.ITEM_LISTED, osstream.EventType.ITEM_RECEIVED_OFFER],
    (event) => {
        console.log(event)
    }
);

**Comment by neicras** [comment]
> @neicras when you create the `OpenSeaStreamClient` instance, what function do you set for `onError` ?
> 
> I have:
> 
> ```js
> const client = new OpenSeaStreamClient({
>   // ... rest of arguments
>   onError: (obj) => console.error(obj.message, obj.error),
> });
> ```

Thanks. adding this line im getting below:

`    at WriteWrap.afterWrite [as oncomplete] (net.js:789:14) errno: 'EPROTO', code: 'EPROTO', syscall: 'write' }
write EPROTO 8635237888:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 70
 { Error: write EPROTO 8635237888:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 70
`

**Comment by rohfle** [comment]
Looks like stream.openseabeta.com only supports TLS1.3

`openssl s_client -connect stream.openseabeta.com:443 -tls1_3` -- works ok
`openssl s_client -connect stream.openseabeta.com:443 -tls1_2` -- fails with alert number 70
`openssl s_client -connect stream.openseabeta.com:443 -tls1_1` -- fails with alert number 70

If you have openssl version older than 1.1.1 or node 12.x you will need to upgrade

Check your version by running node and type the following - DEFAULT_MAX_VERSION should say (at least) 'TLSv1.3'
```
Welcome to Node.js v16.15.0.
Type ".help" for more information.
> const tls = require('tls')
undefined
> tls.DEFAULT_MAX_VERSION
'TLSv1.3'
```

**Comment by neicras** [comment]
> - DEFAULT_MAX_VERSION

Thanks upgrading node fix the issue.
