### ISSUE TITLE
Add order_hash

### ISSUE THREAD

**Issue by mthler** [ProjectOpenSea/stream-js#137]
At the moment the item_received_offer and item_listed payloads missing the order_hash.

Without the order_hash the other events like item_cancelled / item_sold / ... are useless as you can't match any of the events to the offer or listing events.

**Comment by mz-** [comment]
+1

**Comment by itsthedoom** [comment]
Thank you for surfacing, we will look into this.

**Comment by marvinkennis** [comment]
Just leaving a +1 here. Having the order hash is absolutely key. Thanks for investigating!

**Comment by kebian** [comment]
Totally agree.  The events stream is useless without the order hashes and I'd rather not go back to hammering the API endpoint to update order statuses.

**Comment by kebian** [comment]
I'd also like to add that the cancellation event is double useless as it's also triggered when someone cancels a bid against the listing, making it impossible to tell if it was the listing that was cancelled or the bid.

**Comment by gleuch** [comment]
+1 Having the `order_hash` would also be useful for all events, especially `item_cancelled`.

**Comment by guillemcarrion** [comment]
This is the main blocker for us to start using ws endpoint. +1 on adding `order_hash`!

**Comment by anoruxylene** [comment]
+1 Provide `order_hash` 🙏

**Comment by anoruxylene** [comment]
`order_hash` has been added. You can see this in the example below.

```
{
  "event": "item_cancelled",
  "payload": {
    "event_type": "item_cancelled",
    "payload": {
      "base_price": "11000000000000000000",
      "collection": {
        "slug": "doodles-official"
      },
      "event_timestamp": "2022-09-01T11:59:06.000000+00:00",
      "expiration_date": "2022-09-30T09:21:43.000000+00:00",
      "is_private": false,
      "item": {
        "chain": {
          "name": "ethereum"
        },
        "metadata": {
          "animation_url": null,
          "image_url": "https://lh3.googleusercontent.com/iw8BGJUCgaFjhkYaNqBSoLCdSj_Nz5ljX7nRGy77xwBVIpQl2ifie_NYblgGK2_O5NSHKwC2cuVuFL0BsSzQTNIdY80ogcOMQ-b0Rw=s250",
          "metadata_url": "https://opensea.mypinata.cloud/ipfs/QmPMc4tcBsMqLRuCQtPmPe84bpSjrC3Ky7t3JWuHXYB4aS/534",
          "name": "Doodle #534"
        },
        "nft_id": "ethereum/0x8a90cab2b38dba80c64b7734e58ee1db38b8992e/534",
        "permalink": "https://opensea.io/assets/ethereum/0x8a90cab2b38dba80c64b7734e58ee1db38b8992e/534"
      },
      "listing_date": "2022-08-30T09:21:43.000000+00:00",
      "listing_type": null,
      "maker": {
        "address": "0xc53eae0cf7280f073cf168b9b1454e9ab92f0bfb"
      },
      "order_hash": "0x5fb3f27a991dd647d5054ec72df3dcfb7287aff041377e4a8710dbc8df845f7e",
      "payment_token": {
        "address": "0x0000000000000000000000000000000000000000",
        "decimals": 18,
        "eth_price": "1.000000000000000",
        "name": "Ether",
        "symbol": "ETH",
        "usd_price": "1567.410000000000082000"
      },
      "quantity": 1,
      "taker": null,
      "transaction": {
        "hash": "0xfddd06f70dfd22dc84ba80320ad4a20b22be8b3d1ff937079b4ab69fee5b26c1",
        "timestamp": "2022-09-01T11:59:06.000000+00:00"
      }
    },
    "sent_at": "2022-09-01T11:59:17.637191+00:00"
  },
  "ref": null,
  "topic": "collection:doodles-official"
}
```

**Comment by wl506** [comment]
`{
    "event_type": "item_cancelled",
    "payload": {
        "base_price": "2100000000000000000",
        "collection": {
            "slug": "beanzofficial"
        },
        "event_timestamp": "2022-09-20T02:31:59.000000+00:00",
        "expiration_date": null,
        "is_private": false,
        "item": {
            "chain": {
                "name": "ethereum"
            },
            "metadata": {
                "animation_url": null,
                "image_url": "https://lh3.googleusercontent.com/EFikTwH2wb1KSS2AMAsyQh56oaukFXN8J4hasZVfgpLXa7tfCD68whyCt4kS5tIXdJBK-gW-hKrNPH-z6-UeAaIt_ptbwYMByBnGlA=s250",
                "metadata_url": "https://ikzttp.mypinata.cloud/ipfs/QmPZKyuRw4nQTD6S6R5HaNAXwoQVMj8YydDmad3rC985WZ/6472",
                "name": "Bean #6472"
            },
            "nft_id": "ethereum/0x306b1ea3ecdf94ab739f1910bbda052ed4a9f949/6472",
            "permalink": "https://opensea.io/assets/ethereum/0x306b1ea3ecdf94ab739f1910bbda052ed4a9f949/6472"
        },
        "listing_date": null,
        "listing_type": null,
        "maker": null,
        "order_hash": null,
        "payment_token": {
            "address": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
            "decimals": 18,
            "eth_price": "1.000000000000000",
            "name": "Wrapped Ether",
            "symbol": "WETH",
            "usd_price": "1364.579999999999927000"
        },
        "quantity": 1,
        "taker": null,
        "transaction": {
            "hash": "0xa5cde06b69804d36d2425417db90716699b40cd7d3d9236cdae6ae03a80bc43a",
            "timestamp": "2022-09-20T02:31:59.000000+00:00"
        }
    },
    "sent_at": "2022-09-20T02:32:09.020318+00:00"
}`

order_hash is null  @anoruxylene
