### ISSUE TITLE
Error: Unexpected server response: 403

### ISSUE THREAD

**Issue by Slers** [ProjectOpenSea/stream-js#138]
The Stream API was working well until this morning, but since then I have received only 403 server responses.

Anyone else is experiencing this issue?

**Comment by itsthedoom** [comment]
@Slers Thank you for sharing, we are currently investigating this issue. https://status.opensea.io/ 
Please check our Status page for updates https://status.opensea.io/

**Comment by STRsplit** [comment]
I think this should remain open - still receiving the error without a clear guide on how to bail from retries at connecting all of which result in continued 403

**Comment by STRsplit** [comment]
Would like to keep this open as I'm still getting this error rather frequently. I was thinking there would be a way to bail, but after checking out the socket code from Phoenix it looks like the connection will continue to retry. Wondering if there's a way to abort the retries?
