### ISSUE TITLE
Collection offers not being shown

### ISSUE THREAD

**Issue by nftdevabc** [ProjectOpenSea/stream-js#139]
The stream-js websocket (from what I have been able to test) does not show offers that originated from the newly implemented collection offers. As a significant number of offers are beginning to originate from the collection offers, it is important that this data is accessible via the stream-js websocket.

However, practically speaking it does not make sense for a single collection offer to be represented by thousands of orders that are pushed via the streams websocket. Instead it should be formatted as one order with additional data that clearly indicates that it is a collection order and the attributes of the nfts the order applies to.

**Comment by itsthedoom** [comment]
@nftdevabc there is no collection offers API support at this time. I will share your feedback with the team

**Comment by shadmau** [comment]
Is there currently any other way in obtaining collection offers? (e.g. graphql?)
