### ISSUE TITLE
Offers are only partially working

### ISSUE THREAD

**Issue by shea851** [ProjectOpenSea/stream-js#147]
Hi, it seems that through the stream API most offers are not showing.  I see some offers to the OS storefront address, but that's it.

It's really easy to confirm this. Stream offer events for a few seconds. You'll probably see nothing or a few come through for the OS storefront address.

Then hit the events REST API, you will see tons offers from the last second or so.

FYI, this is how I am subscribing. Have tried both ways. (And my code should be good, because listings come through just fine)
`client.onItemReceivedOffer('*', (event)`
`client.onEvents('*', [EventType.ITEM_RECEIVED_OFFER]`

**Comment by shea851** [comment]
Looked into this a bit more. It seems that the websocket is only broadcasting Wyvern offers.
Easy to confirm by hitting the v1.0/Wyvern offer events endpoint, and it lines up.

**Comment by isvidler** [comment]
+1 -- it's obvious that this is not working, which is a major blocker to development

**Comment by mstudda1** [comment]
+1 Same issue

**Comment by hexcreator** [comment]
+1. Related to #174 #187.

**Comment by timmsGithub** [comment]
Interesting...
