### ISSUE TITLE
Stream API Feedback / request for adding data points

### ISSUE THREAD

**Issue by AnGrYxx** [ProjectOpenSea/stream-js#171]
Hi OpenSea API Team,
I am using the stream API for syncing the history of sales, listings and cancelled listings.
I am missing some key data on the payload for cancelled listings https://docs.opensea.io/reference/stream-api-event-schemas#item-cancelled-payload: In case an NFT has multiple listings and there is a cancel event, the stream API does not give a reference to which of those listings is cancelled.
In the event endpoint it has that reference to an active listing if there is an cancel event.
Any plans to add that also to the stream API?
Thx for your feedback / thx for considering!

**Comment by alexismoret** [comment]
Hi @AnGrYxx I have the same problem, but I also have this problem with the event endpoint of the Api, for the moment I cancel a listing by searching it by comparing "from_account", "quantity" and "price" but it's not a very accurate method.
What reference do you use in the "cancelled" event to find the concerned listing ?
