### ISSUE TITLE
The stream api suddenly disconnected and no exception was caught

### ISSUE THREAD

**Issue by qinzhaoyang** [ProjectOpenSea/stream-js#172]
After the program has been running on the server for a period of time, suddenly no data can be monitored!

![image](https://user-images.githubusercontent.com/66238539/182270522-c5a88182-5508-4ef1-8e18-af7ef39ce8b4.png)

**Comment by qinzhaoyang** [comment]
The following error occurred 80 minutes before the program was disconnected:
![image](https://user-images.githubusercontent.com/66238539/182272351-6b73e696-e883-4cdb-b67e-caf8e44cf06b.png)

**Comment by Webber455** [comment]
> The following error occurred 80 minutes before the program was disconnected:
> ![image](https://user-images.githubusercontent.com/66238539/182272351-6b73e696-e883-4cdb-b67e-caf8e44cf06b.png)

Have this error been resolved?

**Comment by NoMeliodas** [comment]
Get the same error with u. Cant get any log
