### ISSUE TITLE
lose some data

### ISSUE THREAD

**Issue by shiyouyuemu2** [ProjectOpenSea/stream-js#176]
I find that opensea often loses some data, which can only be found through the API after a period of time. It seems that the historical missing data has been repaired, but the stream will always lose this part of data and will not push it when the data is supplemented.

**Comment by sanguivore-easyco** [comment]
I've seen this as well, it seems like #99 may have come back.

@rohfle do you still have access to your test client, would you mind running it again? I wonder if results are different for less popular collections (I'm seeing this most often when listening to all collections for all events)
