### ISSUE TITLE
OS Stream limits

### ISSUE THREAD

**Issue by savva312** [ProjectOpenSea/stream-js#185]
Hey, this is not exactly an issue with the package but has to do with OS Stream limits.

1. Is there a limit on how many collections I can subscribe to with 1 API key? I see that we can use a wildcard as collection-slug but are there any limits or performance issues we need to take in consideration?
2. In case there is an outage to the service are the events queued up somewhere and then being send to the websocket once service is back or the events emitted during outage will be lost?
3. How does steam handles block re-organization in case of transfers?

Thank you for your time!

**Comment by buddylindsey** [comment]
From my experience for number 1 I currently subscribe to them all with a wild card, and a single instance manages them well. I immediately push the event into a queue for processing by other code so each action that is executed based on an event is minimal in resources.

I don't remember the numbers but when I was counting it was doing like 200,000 events in an hour during the day. That was over a month ago. Didn't seem to trouble the process.

**Comment by DaryKeruita** [comment]
Very true.

Have the requests queued up and processed by another other code. In 1 minute I get about 8k events.

**Comment by Irantwomiles** [comment]
I asked the devs and they said there isn't a limit, however if it starts getting abused to the point of causing performance issues they will limit the usage much like their REST API.
