### ISSUE TITLE
Few questions regarding streaming API

### ISSUE THREAD

**Issue by sirgarfieldc** [ProjectOpenSea/stream-js#187]
1. Does `onItemListed` only stream  fixed-price listing ?  Can streamed listing contain auction ?   If yes, how can I tell the difference between fixed-price listing & auction ( `listing_type` is always null in the event ) . If no, how should I get streamed new auctions ? 

2. is `onItemReceivedOffer` stream working ?  I set filter to "*" and receive 0 event over a hour.

3. What is the difference between `onItemReceivedOffer` and `onItemReceivedBid`  ?   Is `Offer` only for fixed-price listing and `Bid` for english/dutch auction ?

**Comment by hexcreator** [comment]
Regarding question 2, I also receive zero events from the `item_received_offer` stream with my wrapper even when I subscribe on a per-collection basis. Interested in the answer to question 3.
