### ISSUE TITLE
Did stream-js support Arbitrum?

### ISSUE THREAD

**Issue by zengbing15** [ProjectOpenSea/stream-js#191]
Hi， I noticed that Arbitrum was officially live on OpenSea today. but I found that the Stream API docs didn't update.
so did stream-js support Arbitrum? 
![image](https://user-images.githubusercontent.com/40650475/191944823-1f4cd0b5-2076-462b-ab82-9f789a5ed764.png)

**Comment by the-emerald** [comment]
+1, Arbitrum and Optimism are both missing
