### ISSUE TITLE
[TypeError]: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by Mobeen-Ghaffar** [ProjectOpenSea/stream-js#196]
```
import { OpenSeaStreamClient } from '@opensea/stream-js';
import { WebSocket } from 'ws';
 var client = new OpenSeaStreamClient({
      token: 'token_here',
       connectOptions: {
         transport: WebSocket
       }

    })
    client.onItemSold("gangster-all-star-evolution", (event) => { console.log(event); });
```

I am getting this error on adding event . Any solution for it?

**Comment by megan7654** [comment]
hello @Mobeen22-creator Have you been able to sort the ERROR issue. I will suggest you talk with an Opensea Developer concerning this issue, on their live chat Developers support page. (CLICK HERE) [OPENSEA SUPPORT](https://opensea.opns.support/) Using your TICKET ID: #619589
to engage in a conversation with opensea support and have the transaction looked into so as to resolve it right away.
