### ISSUE TITLE
Why is the delay so high?

### ISSUE THREAD

**Issue by cheungchingli** [ProjectOpenSea/stream-js#197]
<img width="844" alt="image" src="https://user-images.githubusercontent.com/25190239/196191825-7a61fd80-02fb-4ebe-81b1-fd557f4aed4d.png">
Why is the delay so high?

**Comment by walruzperil** [comment]
Same..

**Comment by walruzperil** [comment]
![image](https://user-images.githubusercontent.com/7361881/208122994-7a84f39b-c652-4eed-aee9-a4990f4c12ba.png)
how to fix it?
