### ISSUE TITLE
Multiple collection slug

### ISSUE THREAD

**Issue by Ghijo1** [ProjectOpenSea/stream-js#203]
Hello, is it possible to get events using multiple collection slug?
Thank you

**Comment by vishnu-kvnvv** [comment]
Hi @Ghijo1 , 
You can get events from all the collections by passing `*` as the slug parameter

**Comment by vtemian** [comment]
Is a nice and valid use-case since for example, we want to listen just for 50+ collections, not every single one. Is there any possibility?

**Comment by ryanio** [comment]
why not just call subscribe for each collection? that's all we would do in this package anyway if we were to accept multiple collection slugs
