### ISSUE TITLE
Websocket keeps disconnecting when using Stream API without SDK

### ISSUE THREAD

**Issue by lamolivier** [ProjectOpenSea/stream-js#306]
Hello

We tried to subscribe to the Stream API without using the SDK (in python) and the websocket keeps disconnecting after every 1-2 hours.
We also tried to use the SDK and this issue doesn't happen.

We have this function

```
async def send_heartbeat(socket: Client):

    while True:
        socket.push(topic='phoenix',
                    event='heartbeat',
                    payload={})
        
        await asyncio.sleep(30) 
```

that sends the heartbeats but the websocket keeps disconnecting. 

Do you have an idea why this is happening ? Thank you

By checking the SDK implementation, it doesn't seem that any heartbeat is sent to the server. How you do keep the connection of the websocket alive ?

**Comment by ryanio** [comment]
The phoenix package handles the heartbeat, seems like the default is 10s could you try that instead of 30s?

https://github.com/phoenixframework/phoenix/blob/83f06c7308f03a519b10c079418940efa99331c6/assets/js/phoenix/constants.js#L6

https://github.com/phoenixframework/phoenix/blob/83f06c7308f03a519b10c079418940efa99331c6/guides/howto/writing_a_channels_client.md?plain=1#L64

**Comment by lamolivier** [comment]
Here are some prints in the terminal:

```
at 2023-06-23 01:28:34.539009: 5538
at 2023-06-23 01:28:35.262802: heartbeat with response: {'response': {}, 'status': 'ok'}
at 2023-06-23 01:28:36.822522: 5538
at 2023-06-23 01:28:39.087489: 5538
at 2023-06-23 01:28:40.369804: heartbeat with response: {'response': {}, 'status': 'ok'}
at 2023-06-23 01:28:41.374679: 5538
at 2023-06-23 01:28:43.669673: 5538
at 2023-06-23 01:28:45.482491: heartbeat with response: {'response': {}, 'status': 'ok'}
at 2023-06-23 01:28:45.940678: 5538
at 2023-06-23 01:28:48.229715: 5538
at 2023-06-23 01:28:50.491963: 5538
at 2023-06-23 01:28:50.596058: heartbeat with response: {'response': {}, 'status': 'ok'}
at 2023-06-23 01:28:52.770930: 5538
at 2023-06-23 01:28:55.051449: 5538
at 2023-06-23 01:28:55.707046: heartbeat with response: {'response': {}, 'status': 'ok'}
at 2023-06-23 01:28:57.329734: 5538
at 2023-06-23 01:28:59.614580: 5538
channels: {'collection:boredapeyachtclub': <phxsocket.channel.Channel object at 0x1052f8730>}
Traceback (most recent call last):
phxsocket.client.SocketClosedError
```

The heartbeat is sent every 5 seconds and the total number of messages received is print every 2 seconds.
As you can see, the socket closed even though the heartbeats were sent.


On the contrary, we have the following scenario
```
Heartbeat with response: {'response': {}, 'status': 'ok'}
at 2023-06-22 22:47:19.008965: 0
at 2023-06-22 22:47:21.010257: 0
at 2023-06-22 22:47:23.011819: 0
at 2023-06-22 22:47:25.013497: 0
at 2023-06-22 22:47:27.014765: 1
at 2023-06-22 22:47:29.016771: 1
at 2023-06-22 22:47:31.018751: 1
at 2023-06-22 22:47:33.021774: 2
at 2023-06-22 22:47:35.023251: 3
at 2023-06-22 22:47:37.025170: 3
at 2023-06-22 22:47:39.027777: 3
at 2023-06-22 22:47:41.030337: 3
at 2023-06-22 22:47:43.033396: 3
at 2023-06-22 22:47:45.035883: 3
at 2023-06-22 22:47:47.038595: 3
at 2023-06-22 22:47:49.041453: 3
at 2023-06-22 22:47:51.043767: 3
at 2023-06-22 22:47:53.047357: 3
at 2023-06-22 22:47:55.049842: 3
at 2023-06-22 22:47:57.051932: 3
at 2023-06-22 22:47:59.054169: 3
at 2023-06-22 22:48:01.056862: 3
at 2023-06-22 22:48:03.059156: 3
at 2023-06-22 22:48:05.061486: 3
at 2023-06-22 22:48:07.063586: 3
at 2023-06-22 22:48:09.065402: 3
at 2023-06-22 22:48:11.067850: 3
at 2023-06-22 22:48:13.069012: 3
at 2023-06-22 22:48:15.071190: 3
at 2023-06-22 22:48:17.073631: 3
Heartbeat with response: {'response': {}, 'status': 'ok'}
at 2023-06-22 22:48:19.075478: 3
at 2023-06-22 22:48:21.077806: 3
at 2023-06-22 22:48:23.080044: 3
```

From 22:47:35, there is no new messages and a heartbeat is sent a bit later than 22:48:17. Why the connection did not close as for more than 40 seconds, no message is received and no heartbeat is sent ?

**Comment by ryanio** [comment]
thanks for the additional info. it is indeed strange you are experiencing this when not using steam-js. 

to help debug, could you try using a python phoenix module (eg https://github.com/wwww-wwww/phxsocket) to see if that might help resolve the disconnect issue?

**Comment by lamolivier** [comment]
Thank you for the suggestion. 

However all the code shown above is run by using the phxsocket module. 

We first tried with the python websockets and websocket-client modules and had the same issue. Apparently, phxsocket did not resolve the issue either.

**Comment by ryanio** [comment]
I'm having trouble thinking of other reasons or things to try, especially if our sdk is working fine I'm not sure what could be going on in your setup specifically that could be causing it.

I would just recommend to use our sdk for now.

You can possibly try in another non-JS non-python language to see if it's something with your python setup. I assume you're running this on a server and it's not like your home internet connection is closing after a while.
