### ISSUE TITLE
Getting error 502

### ISSUE THREAD

**Issue by quwest** [ProjectOpenSea/stream-js#316]
Hello,
I'm using python for listen the web socket. When listening the socket after some time (from what I noticed minimum - an hour, maximum - 11 hours) the Server disconnects my client, and when trying to reconnect I get an **error 502** for some time (usually it's nearly two minutes), and after this time socket works well again
<img width="796" alt="image" src="https://github.com/ProjectOpenSea/stream-js/assets/42693782/6f3887ec-0488-4319-92b4-795812ccdd6d">

I've tried a lot of different options. I used the websockets library and phxsocket. The result is the same. Run on different machines (on the server and on a desktop computer). The result is the same (when running simultaneously from different machines disconnects them not at the same moment). Tried to connect through different api keys. The result is the same. I tried connecting to the socket and not join to collections, but the socket is still disconnecting. I tried different intervals for heartbeat, 10, 30 seconds and without it at all. The result is still the same.

If I'm not mistaken, js sdk connects to the socket at address 
**wss://stream.openseabeta.com/socket/websocket?token=API_KEY&vsn=2.0.0**
Could this be the problem? When I try to connect to vsn 2.0.0 The first time I try to receive a message, error 1011 appears (tested with Python libraries, and clients like Postman and Insomnia)

**Comment by ryanio** [comment]
Thanks for reporting and the details, sounds similar to #306, could you try the SDK with your same setup and see if it's something possibly related to the e.g. python libs or setup?

**Comment by quwest** [comment]
**Hi, tried with SDK. That's my code:**

import {EventType, OpenSeaStreamClient} from '@opensea/stream-js';
import { WebSocket } from 'ws';

const client = new OpenSeaStreamClient({
    token: 'xxxxx',
    connectOptions: {
        transport: WebSocket
    }
});
client.connect()

client.onEvents(
    'boredapeyachtclub',
    [EventType.TRAIT_OFFER, EventType.COLLECTION_OFFER, EventType.ITEM_RECEIVED_BID],
    (event) => {
        const currentDate = new Date();
        const hours = currentDate.getHours();
        const minutes = currentDate.getMinutes();
        const seconds = currentDate.getSeconds();
        console.log(`${hours}:${minutes}:${seconds}`);
    }
);

Got logs like this, no errors, but sometimes client rejoining to collection. 
[logs_1.log](https://github.com/ProjectOpenSea/stream-js/files/12357904/logs_1.log)


Ran this same code today, and while running an error occurred, but after some time it started working again, in general this behavior looks similar to when I connect via Python, but it's strange that in the previous run for more than 12 hours there was no error, via Python the connection didn't live that long ever once, could this be related to rejoining to the collection?
[logs_2.log](https://github.com/ProjectOpenSea/stream-js/files/12357901/logs_2.log)
