### ISSUE TITLE
not able to reveal NFTs

### ISSUE THREAD

**Issue by Lozano4** [ProjectOpenSea/stream-js#320]
Hello,
So I was able to mint and buy all of the NFTs that i created to then be able to sell them but for some reason i am not able to reveal the NFTs. Would this be because of the csv file i created? The traits are all showing correctly and everything seems to be good but it just doesnt let me reveal them.

**Comment by ryanio** [comment]
this repostiory is only for opensea's stream-js, you may have better luck asking in the opensea discord dev channel or opening a support ticket.
