### ISSUE TITLE
.onItemListed always listing price as 1 ETH

### ISSUE THREAD

**Issue by Chinch-Bug** [ProjectOpenSea/stream-js#374]
I've got the stream SDK running, subscribed to a few different collections. I've noticed that every time an item_listed event comes through, the eth_price is always 1, even if checking the nft listed in the payload on opensea shows that this is nowhere near the actual price the nft is listed for. Is this a bug with the SDK, or is there something I should be doing to filter these out/fix this on my own end?

**Comment by ryanio** [comment]
eth_price is the price of the token relative to eth, so eth is always 1:1
