### ISSUE TITLE
Missing Events

### ISSUE THREAD

**Issue by pixelpawnshop** [ProjectOpenSea/stream-js#393]
Hello,
I did some testing on the stream api and compared streaming all offers (*) with streaming offers on a specific collection in this case it was boredapeyachtclub. What I have found is that there are missing events even though both streams were up (no disconnection). What is interesting is that the streaming all offers (*) was missing way more events. I tested this couple of times running for up to 30 minutes. In one run the specific offer stream api (boredapeyachtclub) got 21 events for a item and streaming all offers (*) only got 4.

How do you guys handle these missing events? Again I dont mean missing events due to a disconnect I mean simply missing events while the stream is connected. 

Couple questions here:

Are these missing events a local thing? Or are these missing offers a global event? If they are local to a single connection would it make sense to open I dont know 10 websocket connections to make sure no event is missed? 

If the missing of events is global how do you handle them? 

Any idea / help is appreciated!

**Comment by pixelpawnshop** [comment]
I did further testing, and I would say it is nearly impossible that `(*)` is missing significantly more events compared to `(boredapeyachtclub)` only by chance. Especially on those high activity collections nearly every item I compare `(boredapeyachtclub)` always has more events than `(*)`. What could be the reason for this? Also, what workarounds do we have? Is it a viable option to open multiple connections as I mentioned earlier, or would all connections miss the events regardless?

**Comment by ryanio** [comment]
Thanks for the report, we'll look into this. If you can test over a couple days and still see issues please let us know in this thread, and any patterns you may notice. There was some instability earlier today but it should be resolved now.

**Comment by ryanio** [comment]
You can always use the rest api to query events

**Comment by nq** [comment]
Same issue here. Stream API open and lots of missing events. any updates? @pixelpawnshop

**Comment by pixelpawnshop** [comment]
@nq os is aware of the issue but I think fixxing this takes some work. So the only workaround currently is backfilling events using https://docs.opensea.io/reference/list_events_by_collection which kind of sucks as this ofc takes a ton of api call to keep it  updated. But thats the only solution as for now. All the bots using the same approach.
