### ISSUE TITLE
Can we only subscribe to collection event data? 

### ISSUE THREAD

**Issue by ceobitch** [ProjectOpenSea/stream-js#82]
Hey Guys, 

This repo is amazing by far. Very happy you guys made this. Only problem is , I don't see any options to subscribe to wallet addresses events? 

If their any wya we can subscribe to wallet address else besides collections?

**Comment by itsthedoom** [comment]
Hey @ceobitch, Currently we are in beta and currently support the following event types on a per-collection basis:

item listed
item sold
item transferred
item metadata updates
item canceled
item received offer
item received bid

I've noted your request 

> options to subscribe to wallet addresses events

 and will share it with the team.
