### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'WebSocket')

### ISSUE THREAD

**Issue by richApplea** [ProjectOpenSea/stream-js#83]
just followed the instruction.

npm install @opensea/stream-js
install --save-dev @types/phoenix

then try to construct a OpenseaStreamClient and will encounter this issue.

C:\portfolioProgram\nodejs\node_modules\phoenix\priv\static\phoenix.cjs.js:781
    this.transport = opts.transport || global.WebSocket || LongPoll;
                                              ^
TypeError: Cannot read properties of undefined (reading 'WebSocket')

How should i solve this?

**Comment by shryder** [comment]
Having same issue

**Comment by kunnan97** [comment]
having the same issue, however tried it on a react/browser setting, it worked

**Comment by richApplea** [comment]
> worked

is it react/browser setting issue? what did you modify?

**Comment by kunnan97** [comment]
> > worked
> 
> is it react/browser setting issue? what did you modify?

Did not modify anything, was trying on nodejs but got the same error, tried it on create-react-app and it worked

**Comment by juush** [comment]
having similar issue :(

**Comment by juush** [comment]
You need to 
npm i ws
then import WebSocket

add
```connectOptions: {
        transport: WebSocket,
    },```
to OpenSeaStreamClient
```
const {WebSocket} = require('ws')

const wsClient = new OpenSeaStreamClient({
    network: Network.MAINNET,
    apiUrl: "wss://stream.openseabeta.com/socket",
    token: osKey,
    onError: console.error,
    connectOptions: {
        transport: WebSocket,
    },
})
```

**Comment by itsthedoom** [comment]
We recommend switching to Node.js version 16 to make sure common crypto dependencies work. Our minimum supported version is 16.11.0.

Install this package with npm install @opensea/stream-js
NodeJS only: Install the WebSocket library with npm install ws
Install the required dev-dependency to use the Phoenix client for web socket connections npm install --save-dev @types/phoenix

Closing this issue, if you are still running into blockers please let me know we can reopen this issue.
