### ISSUE TITLE
Sell signature is not included in item_listed payloads

### ISSUE THREAD

**Issue by shryder** [ProjectOpenSea/stream-js#85]
Hello, can you guys add order signatures to the `item_listed` payloads? Otherwise we'd have to send an extra http request to fetch it.

**Comment by except** [comment]
Yep I was also looking to avoid extra network calls, would prefer all information needed to complete a transaction in the listing event.

**Comment by itsthedoom** [comment]
@shryder Thank you for the feedback/request. I will share it with the team.

**Comment by sheehan1102** [comment]
Hello! Any updates on this?
