### ISSUE TITLE
Not possible to install package on node versions higher then 16.11.0

### ISSUE THREAD

**Issue by ludovitkapusta** [ProjectOpenSea/stream-js#87]
"We recommend switching to Node.js version 16 to make sure common crypto dependencies work. Our minimum supported version is 16.11.0."

16.11.0 is not minimum supported, its enforced

when trying to install it with 16.13.0 it is not working

you can change your package.json file to support minimal version

```
"engines": {
    "node": ">=16.11.0"
  },
```

**Comment by Meemaw** [comment]
Closing as this has been released.
