### ISSUE TITLE
Add collection name to the listing event

### ISSUE THREAD

**Issue by QuitCrypto** [ProjectOpenSea/stream-js#91]
Currently have to keep an internal mapping of `slug => name`, which requires a series of calls to the polling API to build.  Would be nice for that data to live in the payload for listings.

**Comment by itsthedoom** [comment]
@QuitCrypto Thank you for your feedback. To confirm you would like to see the collection name in the [listing payload](https://docs.opensea.io/reference/stream-api-event-schemas#item-listed-payload)?

```
{
    "event_type": "item_listed",
    "sent_at": "2022-04-25T23:32:14.486643+00:00",
    "payload": {
        "event_timestamp": "2022-04-21T16:46:46.240222+00:00",
        "base_price": "24840000000000000000",
        "expiration_date": "2022-05-17T04:36:50.000000+00:00",
        "is_private": false,
        "listing_date": "2022-04-21T17:10:54.000000+00:00",
        "listing_type": "dutch",
        "maker": { "address": "0xc4b08a8009763dab8c2fb44a59d8f1c23e8c11e5" },
        "payment_token": {
            "address": "0x0000000000000000000000000000000000000000",
            "decimals": 18,
            "eth_price": "1",
            "name": "Ether",
            "symbol": "ETH",
            "usd_price": "3097.57"
        },
        "quantity": 1,
        "taker": null
    }
}
```

**Comment by Cookiezzz** [comment]
I'd like to see it in all payloads. Listing, sale, bid. It saves an API call for getting the name.

**Comment by Cookiezzz** [comment]
In addition I believe the ImageURL sent over wss is the image_preview_url from the API.
The small version (s250 at the end)
Can we get both fields? I prefer larger images.

**Comment by drinksbydrew** [comment]
Same here. I'd really like to get the collection name and full size image URL in the stream.
