### ISSUE TITLE
Add traits to listing API

### ISSUE THREAD

**Issue by QuitCrypto** [ProjectOpenSea/stream-js#92]
This is a nit since the old events endpoint didn't serve traits either, but it would be really nice to include traits in the listing payload.  As it stands, I make a separate call to the `assets` endpoint after receiving an event.  It would be great if I could bypass this step.

**Comment by itsthedoom** [comment]
@QuitCrypto Thank you for the feedback; I've shared it with the team. The Stream API is in beta; we will iterate and improve on it based on user feedback like yours.
